### ISSUE TITLE
Node isn't draggable on a second click

### ISSUE THREAD

**Issue by GNAGONI** [vasturiano/react-force-graph#447]
**Describe the bug**
When you drag a node of a graph (left click on a node, hold the click, and move the mouse)  the second time, the node doesn't move, then the icon appears to be close to the mouse pointer until unclick, and then after unclick the node is mounted to the mouse pointer until the next click. 

**To Reproduce**
1. Go to [sandbox](https://codesandbox.io/s/flamboyant-buck-zdfrqg?file=/src/App.js)
2. Click on a node the first time
3. Click on a node (any node), hold the click, and drag your mouse to any direction outside of a node item
4. See the error

**Expected behavior**
On the second click, the node should behave the same way as it behaved previously: graph reacts on a mouse, nodes are draggable, the graph is rotatable

**Screenshots**
<img width="321" alt="image" src="https://github.com/vasturiano/react-force-graph/assets/30129154/93c7f468-c133-423c-9d16-f374af4271fa">

**Desktop (please complete the following information):**
 - OS: macOS 13.2.1
 - Browser chrome
 - Version 114.0.5735.133

**Comment by vasturiano** [comment]
@GNAGONI thanks for reaching out.

This has just been fixed in a another repo: https://github.com/vasturiano/three-render-objects

The issue was occurring only on chrome and was related to the ability to select the text in the tooltip.

If you upgrade your dependency tree so that it includes the latest version (1.28.6) of `three-render-objects` you shouldn't experience the issue anymore.

Here's a [sandbox](https://codesandbox.io/s/delicate-sound-49tyjx) with the version upgrade.

**Comment by GNAGONI** [comment]
@vasturiano Thanks for the quick response. I tried your option with my application and I'm still facing the problem even with the `three-render-objects` module being installed. Here's the [sandbox](https://codesandbox.io/s/graph-with-legend-f46dmp?file=/src/App.js) with an example where the issue is still reproducible for me. Could you please tell me if you have any ideas about how to solve it?

**Comment by vasturiano** [comment]
@GNAGONI you need to use the latest version of that module: `1.28.6`. In your sandbox you're including `1.28.1`, that's before the fix.

**Comment by GNAGONI** [comment]
@vasturiano Thank you, the issue is fixed. The module `three-render-objects@1.28.6` helped in my project after the update of `yarn.lock` file, so `react-force-graph-3d` used `1.28.6` version of `three-render-object` and not the inner dependency.
